config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('mailscaner.urls', namespace='mailscaner')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailscaner/urls.py
from django.urls import path

from .apps import MailscanerConfig
from . import views


app_name = MailscanerConfig.name


urlpatterns = [
    path('',
         views.MainPageView.as_view(),
         name='main',
         ),
    path('email/create/',
         views.CreateEmailView.as_view(),
         name='create',
         ),
    path('email/delete/<int:pk>/',
         views.DeleteEmailView.as_view(),
         name='delete',
         ),
    path('email/done/',
         views.DoneCreateEmailView.as_view(),
         name='done',
         ),
    path('email/yandex/',
         views.EmailListView.as_view(),
         name='yandex',
         ),
    path('email/gmail/',
         views.EmailListView.as_view(),
         name='gmail',
         ),
    path('email/mail/',
         views.EmailListView.as_view(),
         name='mail',
         ),
    path('email/download/<int:pk>/',
         views.MessagesDownloadView.as_view(),
         name='download',
         ),
    path('email/message/<int:pk>/',
         views.MessageDetailView.as_view(),
         name='message',
         ),
    path('email/messages/<int:pk>/',
         views.MessagesListView.as_view(),
         name='messages',
         ),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .apps import UsersConfig
from . import views


app_name = UsersConfig.name


urlpatterns = [
    path("login/", views.AuthView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('done/', views.DoneRegistationView.as_view(), name='done'),
    path('registration/', views.RegistrationView.as_view(), name='reg'),
    path('user/<str:username>/', views.UserDetailView.as_view(), name='user'),
]

mailscaner/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


CurrentUser = get_user_model()


class Email(models.Model):
    """
    Модель Эмеила
    """
    address = models.EmailField(max_length=254,
                                verbose_name='email',
                                help_text='Email',
                                )
    password = models.CharField(max_length=254,
                                verbose_name='password',
                                help_text='Пароль от почты',
                                )
    last_index = models.BinaryField(null=True,
                                    blank=True,
                                    verbose_name='последний индекс',
                                    help_text='Последний uid выгруженного '
                                    'из почты',
                                    )

    user = models.ForeignKey(CurrentUser,
                             verbose_name='пользователь',
                             on_delete=models.CASCADE,
                             related_name='user_emails',
                             help_text='Текущий пользователь',
                             )

    class Meta:
        verbose_name = 'Email'
        verbose_name_plural = 'Emails'
        constraints = [
            models.UniqueConstraint(
                fields=('user_id', 'address'),
                name='unique_user_address_constraint'
            )
        ]

    def __str__(self):
        return self.address


class File(models.Model):
    """
    Модель файла
    """
    name = models.CharField(max_length=245,
                            verbose_name='имя',
                            help_text='Имя сохраненного файла',
                            )
    file = models.FileField(upload_to='images/',
                            verbose_name='файл',
                            help_text='Файл из сообщения, если есть',
                            null=True,
                            blank=True,
                            max_length=300,
                            )

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("file_detail", kwargs={"pk": self.pk})


class Message(models.Model):
    """
    Модель сообщения из эмеила
    """
    title = models.CharField(max_length=254,
                             verbose_name='тема',
                             help_text='Тема сообщения',
                             null=True,
                             blank=True,
                             )
    sender = models.EmailField(max_length=254,
                               verbose_name='отправитель',
                               help_text='Отправитель письма',
                               null=True,
                               blank=True,
                               )
    date_sending = models.DateTimeField(verbose_name='дата отправки',
                                        help_text='Дата отправки сообщения',
                                        )
    date_receipt = models.DateTimeField(verbose_name='дата получения',
                                        help_text='Дата получения сообщения',
                                        )
    text = models.TextField(verbose_name='текст сообщения',
                            help_text='Текст из сообщения',
                            null=True,
                            blank=True,
                            )

    files = models.ManyToManyField(File,
                                   verbose_name='файлы',
                                   help_text='Сохраненые файлы',
                                   )
    email = models.ForeignKey(Email,
                              on_delete=models.CASCADE,
                              verbose_name='эмеил',
                              related_name='messages',
                              help_text='Эмеил к которому относится сообщение',
                              )

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return str(self.date_receipt)

    def get_absolute_url(self):
        return reverse("message_detail", kwargs={"pk": self.pk})

mailscaner/forms.py
from typing import Any
from django import forms
from django.db.models import Q

from .models import Email
from .regex import check_email_type
from .mail_parser.connections import (
    GmailConnection,
    MailConnection,
    YandexConnection,
)


class EmailCreateFrom(forms.ModelForm):
    """
    Форма создания эмеила
    """
    def __init__(self, *args, **kwargs) -> None:
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Email
        fields = ('address', 'password')

    def clean_address(self):
        address = self.cleaned_data.get('address')
        correct = check_email_type(address)
        if not correct:
            self.add_error('address',
                           'Provide @yandex.ru, @mail.ru or @gmail.com',
                           )
        return address

    def clean(self) -> dict[str, Any]:
        address = self.cleaned_data.get('address')
        password = self.cleaned_data.get('password')
        dublicate = (Email
                     .objects
                     .filter(Q(address=address)
                             & Q(user=self.user))
                     .exists())
        if dublicate:
            self.add_error(
                'address',
                'This Email exists for this user',
            )

        match address.split('@'):
            case _, email_type if email_type == 'yandex.ru':
                YandexConnection.connection(
                    login=address,
                    password=password,
                    form=self,
                )
            case _, email_type if email_type == 'mail.ru':
                MailConnection.connection(
                    login=address,
                    password=password,
                    form=self,
                )
            case _, email_type if email_type == 'gmail.com':
                GmailConnection.connection(
                    login=address,
                    password=password,
                    form=self,
                )

        return self.cleaned_data

    def save(self, commit: bool = ...) -> Any:
        self.instance.user = self.user
        return super().save(commit)

mailscaner/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseBadRequest
from django.views.generic import (TemplateView,
                                  CreateView,
                                  ListView,
                                  DeleteView,
                                  DetailView,
                                  )
from django.contrib.auth import mixins
from django.urls import reverse_lazy
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.template import loader
from django.core.exceptions import PermissionDenied

from .forms import EmailCreateFrom
from .models import Email, Message


class MainPageView(mixins.LoginRequiredMixin,
                   TemplateView):
    """
    View основной страницы
    """
    template_name = 'mailscaner/main.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Main')
        return context


class CreateEmailView(mixins.LoginRequiredMixin,
                      CreateView):
    """
    View создания эмеила
    """
    form_class = EmailCreateFrom
    template_name = 'mailscaner/email_create.html'
    success_url = reverse_lazy('mailscaner:done')

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update(user=self.request.user)
        return kwargs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Create Email')
        return context


class DeleteEmailView(mixins.LoginRequiredMixin,
                      mixins.UserPassesTestMixin,
                      DeleteView):
    """
    View удаления Эмеила
    """
    model = Email
    context_object_name = 'email'
    template_name = 'mailscaner/delete_mail.html'

    def get_success_url(self) -> str:
        return reverse_lazy(f'mailscaner:{self.path}')

    def test_func(self) -> bool | None:
        self.object = self.get_object()
        self.path = self.object.address.split('@')[-1].split('.')[0]
        return self.object.user == self.request.user


class DoneCreateEmailView(mixins.LoginRequiredMixin,
                          TemplateView):
    """
    View завершения создания эмеила
    """
    template_name = 'mailscaner/done.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Done')
        return context


class EmailListView(mixins.LoginRequiredMixin,
                    ListView):
    """
    View просмотра списка эмеилов пользователя
    """
    context_object_name = 'emails'
    template_name = 'mailscaner/emails.html'

    def get_queryset(self) -> QuerySet[Any]:
        path = self.request.path.split('/')
        type_email = '@' + path[-2]
        self.queryset = (Email
                         .objects
                         .filter(Q(address__contains=type_email) &
                                 Q(user=self.request.user)))
        return self.queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='List Emails')
        return context


class MessagesListView(mixins.LoginRequiredMixin,
                       ListView):
    """
    View просмотра списка сообщений от эмеила
    """
    model = Email
    context_object_name = 'messages'
    template_name = 'mailscaner/messages_list.html'
    paginate_by = 50

    def dispatch(self, request, *args, **kwargs):
        email = Email.objects.filter(
            Q(user=self.request.user) &
            Q(pk=self.kwargs['pk'])
        )
        if not email.exists():
            return HttpResponseBadRequest(
                loader.render_to_string(
                    'mailscaner/email_not_found.html',
                    ),
                )
        self.email = email.get()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Any]:
        self.queryset = (Message.objects.filter(
            Q(email=self.email),
        ).prefetch_related('files')
                         .order_by('-date_receipt'))
        return self.queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='ListMessages',
                       email=self.email,
                       )
        return context


class MessageDetailView(mixins.LoginRequiredMixin,
                        DetailView):
    """
    View для просмотра деталей письма
    """
    context_object_name = 'message'
    template_name = 'mailscaner/message_detail.html'

    def get_object(self):
        message = Message.objects.filter(
            Q(pk=self.kwargs['pk'])
        ).select_related('email__user').prefetch_related('files')
        if not message.exists():
            return HttpResponseBadRequest(
                loader.render_to_string(
                    'mailscaner/message_not_found.html',
                    ),
                )
        self.object = message.get()
        if self.request.user != self.object.email.user:
            raise PermissionDenied(
                'You not have permissions for this action',
                )
        return self.object


class MessagesDownloadView(mixins.LoginRequiredMixin,
                           mixins.UserPassesTestMixin,
                           DetailView):
    """
    View для загрузки сообщений из эмеил
    """
    model = Email
    context_object_name = 'email'
    template_name = 'mailscaner/download.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Download')
        return context

    def test_func(self) -> bool | None:
        object_ = self.get_object()
        return object_.user == self.request.user

mailscaner/templates/includes/in_download.html
{% load static %}
<div class="container">
    <a id="back" href="{% url 'mailscaner:main' %}">Back</a>
    <h3 class="text-center">Download Messages from {{ email }}</h3>
    <h5 class="status text-center"></h5>
    <div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100">
        <div class="value text-center z-3 position-absolute d-flex" style="left: 50%;">
            <div class="loads"></div>
            \
            <div class="wait"></div>
        </div>
        <div class="progress-bar bg-success text-dark">
        </div>
    </div>
    <div class="card mt-2 p-2">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Sender</th>
                    <th scope="col">Date Seding</th>
                    <th scope="col">Date Receipt</th>
                    <th scope="col">Text</th>
                    <th scope="col">File</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
{{ email.pk|json_script:"email_id" }}

mailscaner/templates/includes/in_email_create.html
{% load static %}
<div class="container">
    <a href="{% url 'mailscaner:main' %}">Back</a>
    <h3 class="text-center">Create Email</h3>
    <div class="card mt-2 p-2">
        <form class="offset-4 col-md-4 card-body mb-4 p-2" action="{% url 'mailscaner:create' %}" method="post">
            {% csrf_token %}
            <div class="card-title">
                <p class="text-center" style="font-size: 15px;">
                    <strong>Provide "@yandex.ru", "@mail.ru" or "@gmail.com" another type is blocking</strong>
                </p>
            </div>
            <div class="card-body">
        
                    <input type="hidden" name="next" value="{{ next }}" />
        
                    {% if form.non_field_errors %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% endif %}
                        <div class="form-floating">
                            <input class="form-control" type="text" name="address" placeholder="{{ form.address.label }}" autofocus="true" required id="id_address">
                            <label class="form-label text-secondary" for="id_address">* {{ form.address.label }}</label>
                        </div>
                        <div class="form-error">{{ form.address.errors }}</div>
            
                        <div class="form-floating mt-2">
                            <input class="form-control" type="password" placeholder="{{ form.password.label }}" name="password" required id="id_password">
                            <label class="form-label text-secondary" for="id_password">* {{ form.password.label }}</label>
                        </div>
                        <div class="form-error">{{ form.password.errors }}</div>
                        
                    <div class="col-md-12">
                        <button class="btn mt-2 border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" type="submit">Submit</button>
                    </div>
            </div>
            <div class="card-footer">
                <h5>NOTE:</h5>
                <p>To create mail, you need to go to the website of your postal company and <strong>set the settings.</strong> That allow the use of IMAP and create a <strong>special password</strong> for using it here.</p>
            </div>
        </form>
    </div>
</div>

mailscaner/templates/includes/in_emails.html
{% load static %}
<div class="container">
    <a href="{% url 'mailscaner:main' %}">Back</a>
    <h3 class="text-center">List Emails</h3>
    <div class="card mt-2 p-2">
        {% if emails %}
        <ul class="list-group">
            {% for email in emails %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                            <strong>{{ email.address }}</strong>
                            <a class='btn border' href="{% url 'mailscaner:download' email.pk %}">
                                UploadData
                            </a>
                            <a class='btn border' href="{% url 'mailscaner:messages' email.pk %}">
                                Show list
                            </a>                          
                            <a class="btn btn-danger border" href="{% url 'mailscaner:delete' email.pk %}">
                                Delete
                            </a>
                        </div>
                    </li>
            {% endfor %}
        </ul>
        {% else %}
        <div class="text-center">
            <h5>List is empty</h5>
        </div>
        {% endif %}
    </div>
</div>

mailscaner/templates/includes/in_main.html
<div class="container">
    <div class="text-end">
        <a class="btn border" href="{% url 'mailscaner:create' %}">Add Email</a>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card m-5 p-5">
            <a href="email/gmail/">Gmail</a>
        </div>
        <div class="card m-5 p-5">
            <a href="email/yandex/">Yandex</a>
        </div>
        <div class="card m-5 p-5">
            <a href="email/mail/">Mail.ru</a>
        </div>
    </div>
</div>

mailscaner/templates/includes/in_message.html
{% load static %}
<div class="container">
    <a href="{% url 'mailscaner:messages' message.email.pk %}">Back</a>
    <h3 class="text-center mb-4">Message from {{ message.sender }}</h3>
    <div class="card mt-2 p-2">
        <div class="d-flex justify-content-around">
            <div>
                <strong>FROM: </strong>{{ message.sender }}
            </div>
            <div class="d-flex flex-column">
                <strong>TIME_SENDING: </strong>{{ message.date_sending }}
                <strong>TIME_RECEIPT: </strong>{{ message.date_receipt }}
            </div>
        </div>
        <hr class="mt-1">
        <div class="card-body">
            <div>
                <strong>TITLE: </strong>{{ message.title }}
            </div>
            <div>
                <strong>TEXT: </strong>{{ message.text }}
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex flex-column">
                <strong>FILES: </strong>
                {% for file in message.files.all %}
                <a href="http://localhost:8000/media/images/{{ file.name }}">{{ file.name }}</a>
                {% empty %}
                no files
                {% endfor %}
            </div>
        </div>
    </div>
</div>

mailscaner/templates/includes/in_messages.html
{% load static %}
<div class="container">
    <a href="{% url 'mailscaner:main' %}">Back</a>
    <h3 class="text-center mb-4">Messages from {{ email.address }}</h3>
    <div class="card mt-2 p-2">
        <div class="row p-3">
            <div class="col"><strong>Title</strong></div>
            <div class="col"><strong>Sender</strong></div>
            <div class="col"><strong>Date Sending</strong></div>
            <div class="col"><strong>Date Receipt</strong></div>
            <div class="col"><strong>Text</strong></div>
            <div class="col"><strong>Files</strong></div>
        </div>
        {% for message in messages %}
        <a class="card m-2 p-1" href="{% url 'mailscaner:message' message.pk %}">
            <div class="row">
                <div class="col text-break" style="font-size: 12px;">{{ message.title|truncatechars:50 }}</div>
                <div class="col text-break" style="font-size: 12px;">{{ message.sender }}</div>
                <div class="col text-break" style="font-size: 12px;">{{ message.date_sending }}</div>
                <div class="col text-break" style="font-size: 12px;">{{ message.date_receipt }}</div>
                <div class="col text-break" style="font-size: 12px;">{{ message.text|truncatechars:100 }}</div>
                <div class="col text-break" style="font-size: 12px;">
                {% for file in message.files.all %}
                    <div class="d-flex flex-column">
                        {{ file.name }}
                    </div>
                {% empty %}
                    Empty
                {% endfor %}
                </div>
            </div>
        </a>
        {% empty %}
            <h5 class="text-center">Not have messages yet</h5>
        {% endfor %}
    </div>
</div>