config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('mailscaner.urls', namespace='mailscaner')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .apps import UsersConfig
from . import views


app_name = UsersConfig.name


urlpatterns = [
    path("login/", views.AuthView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('done/', views.DoneRegistationView.as_view(), name='done'),
    path('registration/', views.RegistrationView.as_view(), name='reg'),
    path('user/<str:username>/', views.UserDetailView.as_view(), name='user'),
]

mailscaner/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


CurrentUser = get_user_model()


class Email(models.Model):
    """
    Модель Эмеила
    """
    address = models.EmailField(max_length=254,
                                verbose_name='email',
                                help_text='Email',
                                )
    password = models.CharField(max_length=254,
                                verbose_name='password',
                                help_text='Пароль от почты',
                                )
    last_index = models.BinaryField(null=True,
                                    blank=True,
                                    verbose_name='последний индекс',
                                    help_text='Последний uid выгруженного '
                                    'из почты',
                                    )

    user = models.ForeignKey(CurrentUser,
                             verbose_name='пользователь',
                             on_delete=models.CASCADE,
                             related_name='user_emails',
                             help_text='Текущий пользователь',
                             )

    class Meta:
        verbose_name = 'Email'
        verbose_name_plural = 'Emails'
        constraints = [
            models.UniqueConstraint(
                fields=('user_id', 'address'),
                name='unique_user_address_constraint'
            )
        ]

    def __str__(self):
        return self.address


class File(models.Model):
    """
    Модель файла
    """
    name = models.CharField(max_length=245,
                            verbose_name='имя',
                            help_text='Имя сохраненного файла',
                            )
    file = models.FileField(upload_to='images/',
                            verbose_name='файл',
                            help_text='Файл из сообщения, если есть',
                            null=True,
                            blank=True,
                            max_length=300,
                            )

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("file_detail", kwargs={"pk": self.pk})


class Message(models.Model):
    """
    Модель сообщения из эмеила
    """
    title = models.CharField(max_length=254,
                             verbose_name='тема',
                             help_text='Тема сообщения',
                             null=True,
                             blank=True,
                             )
    sender = models.EmailField(max_length=254,
                               verbose_name='отправитель',
                               help_text='Отправитель письма',
                               null=True,
                               blank=True,
                               )
    date_sending = models.DateTimeField(verbose_name='дата отправки',
                                        help_text='Дата отправки сообщения',
                                        )
    date_receipt = models.DateTimeField(verbose_name='дата получения',
                                        help_text='Дата получения сообщения',
                                        )
    text = models.TextField(verbose_name='текст сообщения',
                            help_text='Текст из сообщения',
                            null=True,
                            blank=True,
                            )

    files = models.ManyToManyField(File,
                                   verbose_name='файлы',
                                   help_text='Сохраненые файлы',
                                   )
    email = models.ForeignKey(Email,
                              on_delete=models.CASCADE,
                              verbose_name='эмеил',
                              related_name='messages',
                              help_text='Эмеил к которому относится сообщение',
                              )

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return str(self.date_receipt)

    def get_absolute_url(self):
        return reverse("message_detail", kwargs={"pk": self.pk})

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    """
    Модель пользователя
    """
    image = models.ImageField(upload_to='users/',
                              blank=True,
                              null=True,
                              verbose_name='Изображение',
                              help_text='Изображение пользователя',
                              )

    emails = models.ManyToManyField("mailscaner.Email",
                                    verbose_name='эмеилы',
                                    help_text='Эмеилы '
                                    'принадлежащие пользователю',
                                    related_name='users',
                                    )

    class Meta:
        db_table = 'user'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def get_absolute_url(self):
        return reverse("users:user", kwargs={"username": self.username})

users/forms.py
from django.contrib.auth.forms import (AuthenticationForm,
                                       UserCreationForm,
                                       )
from django.contrib.auth import get_user_model
from django import forms


class UserAuthenticationForm(AuthenticationForm):
    """
    Форма Аутентификации пользователя
    """
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'password',)


class UserRegisterForm(UserCreationForm):
    """
    Форма Регистрация пользователя
    """

    class Meta:
        model = get_user_model()
        fields = ('username',
                  'email',
                  'password1',
                  'password2',
                  )

users/views.py
from typing import Any
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
                                  DetailView,
                                  TemplateView,
                                  )

from .forms import (UserRegisterForm,
                    UserAuthenticationForm,
                    )


UserModel = get_user_model()


class AuthView(LoginView):
    """
    View Аутентификации
    """
    template_name = 'users/login.html'
    form_class = UserAuthenticationForm

    def get_success_url(self) -> str:
        return reverse_lazy('mailscaner:main')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Authentication')
        return context


class RegistrationView(CreateView):
    """
    View Регистрации пользователя
    """
    template_name = 'users/registration.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:done')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title='Registration')
        return context


class UserDetailView(DetailView):
    """
    View профиля пользователя
    """
    model = UserModel
    template_name = 'users/user.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'current_user'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(title=self.object.username)
        return context


class DoneRegistationView(TemplateView):
    """
    View завершения регистрации
    """
    template_name = 'users/done.html'

users/templates/includes/in_login.html
{% load static %}

<div class="container">
    <div>
        <div class="d-flex align-items-center">
            <div class="card offset-4 col-4 p-3">
                <div class="card-title">
                    <h4>Authentication</h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="text" value="{{ next }}"/>
                        {% if form.non_field_errors %}
                            <div class="form-error" style="font-size: 14px;"><strong>{{ form.non_field_errors }}</strong></div>
                        {% endif %}
                        <p>
                            <label class="form-label" for="id_username">Login</label>
                            <input class="form-control" type="text" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} name="username" autofocus="true" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
                        </p>
                        <p>
                            <label class="form-label" for="id_password">Password</label>
                            <input class="form-control" type="password" name="password" autocomplete="current-password" required id="id_password">
                        </p>
                        <button class="offset-1 col-md-10 btn btn-success border mt-2" type="submit">Enter</button>
                        <div class="d-flex justify-content-center">
                            <a class="btn border btn-sm mt-2 ms-4" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" href="{% url 'users:reg' %}">Registration</a>
                        </div>
                    </form>
                </div>
                <div class="card-footer mt-4">
                    <p style="font-size: 12px;">This service provides access to download your messages from various Email services.</p>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/includes/in_registration.html
{% load static %}
<a href="{% url 'users:login' %}">Back</a>
<h3 class="text-center">Registration</h3>
<div class="card mt-2 p-2">
    <form class="offset-3 col-md-6 card-body mb-4 p-2" action="{% url 'users:reg' %}" method="post">
        <div class="card-title">
            <p class="text-center" style="font-size: 15px;">
                <strong>Form registration, * is required</strong>
            </p>
        </div>
        {% csrf_token %}

            <input type="hidden" name="next" value="{{ next }}" />

            {% if form.non_field_errors %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% endif %}
                <div class="form-floating">
                    <input class="form-control" type="text" name="username" placeholder="{{ form.username.label }}" autofocus="true" required id="id_username">
                    <label class="form-label text-secondary" for="id_username">* {{ form.username.label }}</label>
                </div>
                <div class="form-error">{{ form.username.errors }}</div>
    
                <div class="form-floating mt-2">
                    <input class="form-control" type="email" {% if form.email.value %}value="{{ form.email.value }}"{% endif %} name="email" placeholder="{{ form.email.label }}" maxlength="254" {% if value.email %}value="{{ value.email }}"{% endif %} id="id_email">
                    <label class="form-label text-secondary" for="id_email">{{ form.email.label }}</label>
                </div>
                <div class="form-error">{{ form.email.errors }}</div>
    
                <div class="form-floating mt-2">
                    <input class="form-control" type="password" placeholder="{{ form.password1.label }}" name="password1" required id="id_password1">
                    <label class="form-label text-secondary" for="id_password1">* {{ form.password1.label }}</label>
                </div>
                <div class="form-error">{{ form.password1.errors }}</div>
                
                <div class="form-floating mt-2">
                    <input class="form-control" type="password" placeholder="{{ form.password2.label }}" name="password2" required id="id_password2">
                    <label class="form-label text-secondary" for="id_password2">* {{ form.password2.label }}</label>
                </div>
                <div class="form-error">{{ form.password2.errors }}</div>    
            <div class="col-md-12">
                <button class="btn mt-2 border" style="box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);" type="submit">Submit</button>
            </div>
    </form>
    <div class="card-footer">
        <div class="offset-2 col-md-8">
            <p style="font-size: 14px;"><strong>By registering you agree to <a href="">the processing of personal data and the collection of statistics</a></strong></p>
        </div>
    </div>
</div>

users/templates/includes/in_user.html
{% load static %}
<div class="container">
  <div class="card p-3">
    <div class="offset-1 col-10">

      <h3 class="p-2">
          Personal data user
      </h3>
      <div class="card bg-body-tertiary m-1 p-2" style="border-radius: 8px; box-shadow: 0 1px 2px 0 rgba(0,0,0,.16);">
          <div class="card-body p-3 card_big_style">
              <div class="my-3 card_big_images">
                      {% if current_user.image %}
                      <img src="{{ current_user.image.url }}" class="d-block w-auto card-style-image" alt="{{ current_user.username }}">
                      {% else %}
                      <img src="{% static 'images/image_not_found.jpeg' %}" class="d-block w-auto card-style-image" alt="{{ current_user.username }}">
                      {% endif %}
              </div>
              <div style="grid-area: spec-brand">
                <div class="d-flex justify-content-between">
                  <div>
                    <p style="line-height: .9375rem; font-size: .8125rem; font-weight: 700;">Login: <strong>{{ current_user.username }}</strong></p>
                    <p style="font-size: .80rem; line-height: .6875rem;">Date registration: {{ current_user.date_joined }}</p>
                  </div>
                </div>
              </div>
      
              {% if request.user == current_user or request.user.is_staff %}
              <div class="d-flex flex-column" style="grid-area:stat;">
                <div class="d-flex">
                  <div style="font-size: .80rem; line-height: 1.250rem;">Email: {% if current_user.email %}{{ current_user.email }}{% else %} not found{% endif %}</div>
                </div>
                {% endif %}
              </div>
          </div>
      </div>
    </div>
  </div>
</div>